

export const GETUSERLOGIN = "GETUSERLOGIN"
export const GETUSERLOGINSUCCESS = "GETUSERLOGINSUCCESS"
export const GETUSERLOGINFAIL = "GETUSERLOGINFAIL"

export const POSTUSERREQ = "POSTUSERREQ"
export const POSTREQSUCESS = "POSTREQSUCESS"
export const POSTREQFAIL = "POSTREQFAIL"